/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppUserRouteImport } from './routes/_app/user'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppDatahubIndexRouteImport } from './routes/_app/datahub/index'
import { Route as AppSessionStartSessionRouteImport } from './routes/_app/session/start-session'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppDatahubSubjectIdIndexRouteImport } from './routes/_app/datahub/$subjectId/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminGroupsIndexRouteImport } from './routes/_app/admin/groups/index'
import { Route as AppAdminUsersCreateRouteImport } from './routes/_app/admin/users/create'
import { Route as AppAdminGroupsCreateRouteImport } from './routes/_app/admin/groups/create'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserRoute = AppUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDatahubIndexRoute = AppDatahubIndexRouteImport.update({
  id: '/datahub/',
  path: '/datahub/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessionStartSessionRoute = AppSessionStartSessionRouteImport.update({
  id: '/session/start-session',
  path: '/session/start-session',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDatahubSubjectIdIndexRoute =
  AppDatahubSubjectIdIndexRouteImport.update({
    id: '/datahub/$subjectId/',
    path: '/datahub/$subjectId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminGroupsIndexRoute = AppAdminGroupsIndexRouteImport.update({
  id: '/admin/groups/',
  path: '/admin/groups/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsersCreateRoute = AppAdminUsersCreateRouteImport.update({
  id: '/admin/users/create',
  path: '/admin/users/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminGroupsCreateRoute = AppAdminGroupsCreateRouteImport.update({
  id: '/admin/groups/create',
  path: '/admin/groups/create',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/setup': typeof SetupRoute
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/user': typeof AppUserRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/session/start-session': typeof AppSessionStartSessionRoute
  '/datahub': typeof AppDatahubIndexRoute
  '/admin/groups/create': typeof AppAdminGroupsCreateRoute
  '/admin/users/create': typeof AppAdminUsersCreateRoute
  '/admin/groups': typeof AppAdminGroupsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/datahub/$subjectId': typeof AppDatahubSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/dashboard': typeof AppDashboardRoute
  '/user': typeof AppUserRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/session/start-session': typeof AppSessionStartSessionRoute
  '/datahub': typeof AppDatahubIndexRoute
  '/admin/groups/create': typeof AppAdminGroupsCreateRoute
  '/admin/users/create': typeof AppAdminUsersCreateRoute
  '/admin/groups': typeof AppAdminGroupsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/datahub/$subjectId': typeof AppDatahubSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/user': typeof AppUserRoute
  '/auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/session/start-session': typeof AppSessionStartSessionRoute
  '/_app/datahub/': typeof AppDatahubIndexRoute
  '/_app/admin/groups/create': typeof AppAdminGroupsCreateRoute
  '/_app/admin/users/create': typeof AppAdminUsersCreateRoute
  '/_app/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/datahub/$subjectId/': typeof AppDatahubSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/setup'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/user'
    | '/auth/login'
    | '/'
    | '/admin/settings'
    | '/session/start-session'
    | '/datahub'
    | '/admin/groups/create'
    | '/admin/users/create'
    | '/admin/groups'
    | '/admin/users'
    | '/datahub/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/user'
    | '/auth/login'
    | '/'
    | '/admin/settings'
    | '/session/start-session'
    | '/datahub'
    | '/admin/groups/create'
    | '/admin/users/create'
    | '/admin/groups'
    | '/admin/users'
    | '/datahub/$subjectId'
  id:
    | '__root__'
    | '/_app'
    | '/setup'
    | '/_app/about'
    | '/_app/contact'
    | '/_app/dashboard'
    | '/_app/user'
    | '/auth/login'
    | '/_app/'
    | '/_app/admin/settings'
    | '/_app/session/start-session'
    | '/_app/datahub/'
    | '/_app/admin/groups/create'
    | '/_app/admin/users/create'
    | '/_app/admin/groups/'
    | '/_app/admin/users/'
    | '/_app/datahub/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SetupRoute: typeof SetupRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/user': {
      id: '/_app/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/datahub/': {
      id: '/_app/datahub/'
      path: '/datahub'
      fullPath: '/datahub'
      preLoaderRoute: typeof AppDatahubIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/session/start-session': {
      id: '/_app/session/start-session'
      path: '/session/start-session'
      fullPath: '/session/start-session'
      preLoaderRoute: typeof AppSessionStartSessionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/datahub/$subjectId/': {
      id: '/_app/datahub/$subjectId/'
      path: '/datahub/$subjectId'
      fullPath: '/datahub/$subjectId'
      preLoaderRoute: typeof AppDatahubSubjectIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/groups/': {
      id: '/_app/admin/groups/'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AppAdminGroupsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/users/create': {
      id: '/_app/admin/users/create'
      path: '/admin/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AppAdminUsersCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/groups/create': {
      id: '/_app/admin/groups/create'
      path: '/admin/groups/create'
      fullPath: '/admin/groups/create'
      preLoaderRoute: typeof AppAdminGroupsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppContactRoute: typeof AppContactRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppUserRoute: typeof AppUserRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppSessionStartSessionRoute: typeof AppSessionStartSessionRoute
  AppDatahubIndexRoute: typeof AppDatahubIndexRoute
  AppAdminGroupsCreateRoute: typeof AppAdminGroupsCreateRoute
  AppAdminUsersCreateRoute: typeof AppAdminUsersCreateRoute
  AppAdminGroupsIndexRoute: typeof AppAdminGroupsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppDatahubSubjectIdIndexRoute: typeof AppDatahubSubjectIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppContactRoute: AppContactRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppUserRoute: AppUserRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppSessionStartSessionRoute: AppSessionStartSessionRoute,
  AppDatahubIndexRoute: AppDatahubIndexRoute,
  AppAdminGroupsCreateRoute: AppAdminGroupsCreateRoute,
  AppAdminUsersCreateRoute: AppAdminUsersCreateRoute,
  AppAdminGroupsIndexRoute: AppAdminGroupsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppDatahubSubjectIdIndexRoute: AppDatahubSubjectIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  SetupRoute: SetupRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
